on:
  push:
    branches:
      - master

jobs:
  update_lean_xyz_branch:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Update lean-x.y.z branch
    steps:

    - name: checkout project
      uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
      with:
        fetch-depth: 0

    - name: update branch
      uses: leanprover-contrib/update-versions-action@f0ead25c644d4d4cd37d46752c4e2ee4d9044060 # master as of 2026-09-28