on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  upgrade_lean:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    name: Bump Lean and dependency versions
    steps:
      - name: checkout project
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
      - name: upgrade Lean and dependencies
        uses: leanprover-contrib/lean-upgrade-action@d8031fe6ff31bfbe490b7acf6604e733a8b4e13b # master as of 2026-09-28
        with:
          repo: ${{ github.repository }}
          access-token: ${{ secrets.GITHUB_TOKEN }}